"""add language to posts

Revision ID: 99df47340cc6
Revises: 814147c56cbf
Create Date: 2025-09-23 16:09:21.763122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99df47340cc6'
down_revision = '814147c56cbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###
